### PR TITLE
Add Sublime Text 4 Support

### PR DESCRIPTION
**Pull request by heyvito**
Hi there, folks!
First, thank you so much for maintaining  SideBarEnhancements!

I noticed the package was having some problems with ST4 (reported by #426), and decided to try to figure out why, specially since no API this package uses was heavily modified.

Well, it happens ST4 have two distinct plugin_hosts! And SideBarEnhancements was being loaded by the older one, so nothing actually crashed, but overrides from `SideBarDefaultDisable.py` weren't really honoured.

This can be fixed by adding an extra `.python-version` file so Sublime loads the plugin using the new host and, voilà, default items are gone. I also downloaded ST3 again to check if this may end up breaking something on the previous version, and I haven't noticed anything weird.
It may be worth mentioning I haven't extensively tested the extension on ST4, but I can confirm that all major features are working as expected.

Maintainers: I'm not really acquainted on how distribution through PackageControl happens, so I'm not sure whether it would pick this new file. I noticed some folks commenting that packages having dependencies will always be loaded in the older plugin host, but as far as I can tell, it's not the case of this one.

### CODE REVIEW

**Comment by titoBouzout** [comment]
Ah pretty cool, always been pretty puzzled about that!

**Comment by titoBouzout** [comment]
PackageControl seems to get the version from the git tags, so I pushed a new tag, thanks!

**Comment by heyvito** [comment]
Awesome! Just installed through PackageControl, and it's working as expected 🙌🏻 
Thanks!

**Comment by DanHulton** [comment]
Amazing tyvm!

**Pull request merged**
