### PR TITLE
auto add folders for opened files

### PR DESCRIPTION
**Pull request by randy3k**
This is the PR of what was [discussed](https://github.com/titoBouzout/SideBarEnhancements/issues/190)
I have set the defaults to true, not sure if it is a good decision.

### CODE REVIEW

**Comment by titoBouzout** [comment]
Thanks!

**Comment by titoBouzout** [comment]
If people does not complain is a good idea :P I may turn it off for when the project has folders open

**Comment by randy3k** [comment]
I just realize ST could become very slow when editing `~/.bashrc` or any file under the user directory due to the heavy indexing when the user directory is added as a project folder. We might need to add a blacklist of directories for performance.

**Comment by titoBouzout** [comment]
Okei, I guess we can add a new preference, a list of directories to blacklist, and we just iterate it Normalizing both values, the directory and the blacklist with .replace('\', '/') so it plays friendly with Windows

**Pull request merged**
