### PR TITLE
For 'Open in Browser', add support for the user's primary browser

### PR DESCRIPTION
**Pull request by ghost**
On my system, the default settings of 'Open in Browser' are very surprising: it will open Chrome even though it's not my primary browser.

This pull request will use the user's primary browser by default. It uses Python's webbrowser module to do the hard work.

The user can of course still control which browser is opened, by changing the SideBar settings.

### CODE REVIEW

**Comment by titoBouzout** [comment]
Hello! Alrady includes support for default browser by leaving the browser name blank. (ST3)

**Comment by ghost** [comment]
Okay, but in ST2, leaving it blank doesn't work. That's why I created this pull request.

screen shot 2013-12-18 at 13 02 20

**Comment by titoBouzout** [comment]
Yep, ST2 branch is deprecated. I'm sorry.

**Comment by ghost** [comment]
I don't own a ST3 license so I'm using the trial to test this. In ST3, 'Open in Browser' using a blank browser name simply does nothing at all, not even an error message is shown.

**Comment by titoBouzout** [comment]
Try setting the path in the portable_browser setting.

**Comment by ghost** [comment]
Yes, but the idea is that the user's default browser is used without having to configure it. Python knows how to do this using the built-in webbrowser module. It's very easy to use, like I did in my pull request.

**Comment by titoBouzout** [comment]
yes, I know, this package at first used that approach, but have had too many people having problems with the opened browser, they wanted another browser :P

**Comment by ghost** [comment]
That's why the setting exists in the first place :P The default is to use the default browser, and if they don't want the default, they can change the setting.

But right now, the default is to not open any browser at all! (Or for ST2, to open Chrome even if it's not the default, or even when it's not installed.)

**Comment by titoBouzout** [comment]
Here is, you should add the OSX special command that opens the browser of the OS, no python webbrowser :P 
https://github.com/titoBouzout/SideBarEnhancements/blob/st3/SideBar.py#L1503-L1512

Give it a try, it miss the OSX case.

**Comment by titoBouzout** [comment]
Just please keep in mind I don't update ST2 anymore, just the st3 branch.

**Comment by ghost** [comment]
Why not simplify the default case to `webbrowser.open_new_tab()`? Webbrowser always opens the user's default browser.

`start` for Windows, `xdg-open` for Linux and `open` for OSX will do the same thing but require more lines of code, so why make this part more complex than necessary?

**Comment by titoBouzout** [comment]
open for OSX looks like it will work.

**Comment by ghost** [comment]
What's wrong with `webbrowser`?

**Comment by titoBouzout** [comment]
It does not work as expected. I can't remember, it was a long time ago. There is no problem with the one line command.

**Comment by ghost** [comment]
The current approach is actually much more than a one line command. In cd06e8f09aaee88c42fa8198cd881684c91c388a (current st3 branch) it's 10 lines, and that's even without OSX support. Using `webbrowser` takes only 5 lines (import, try, webbrowser.open, except, error message) and supports all systems where ST runs.

I'd love to see a case where `webbrowser` fails. You say it doesn't work as expected, but I've never seen that happen. It works fine for local paths as well as URLs.

In any case, the user can always specify a different browser.

**Comment by titoBouzout** [comment]
The code you quote is not related to the discussed issue. I already quote the exact portion of code that will run if the user wants the "default browser".

**Comment by ghost** [comment]
Yes, that's https://github.com/titoBouzout/SideBarEnhancements/blob/st3/SideBar.py#L1503-L1512, correct? Maybe I'm counting wrong, but to me that highlights 10 lines. That will be 13 if OSX is supported.

**Comment by titoBouzout** [comment]
In case we missed something, we are discussing about a file with 1550 lines. Ten of twenty lines.. makes no difference.

**Comment by ghost** [comment]
You're saying it's okay to have bloated code if the other code is also big?

This will improve the situation. It's a first step!

**Comment by titoBouzout** [comment]
FYI: I'm much more worried if the file will open in the browser, than about the number of lines.

**Comment by ghost** [comment]
The file _will_ open in the browser. That's the entire purpose of Python's `webbrowser` module! If `webbrowser` would fail, why would the current method work?

**Comment by titoBouzout** [comment]
http://www.sublimetext.com/forum/viewtopic.php?f=3&t=10595&start=0&hilit=webbrowser

**Comment by titoBouzout** [comment]
Matthijs with all my respects, I'm not interested to discuss webbrowser,

**Comment by ghost** [comment]
Okay. Last I will say, in reply to the forum post you linked: it apparently failed due to gnome-open being replaced by something newer. But the same will happen to SideBarEnhancements if xdg-open is replaced in the future. At least by using Python's implementation, you don't have to fix the problem yourself.

**Comment by titoBouzout** [comment]
Im pretty sure there is some plugin using webbrowser and just that, why not use that??

**Comment by ghost** [comment]
I think you misunderstand. I'm a ST2 SideBarEnhancements user and I rarely use 'Open in Browser'. But the one time I did use it, I was surprised by the default behavior. Then I started looking deeper into this function and added the default browser code with which this pull request started out with. As a programmer, and as someone who cares about details, I dislike unnecessary code. That's why I recommended replacing the default browser detection code with webbrowser.

**Comment by titoBouzout** [comment]
> As a programmer, and as someone who cares about details, I dislike unnecessary code. That's why I recommended replacing the default browser detection code with webbrowser.

Thanks for your recommendation. No misunderstanding.. SideBarEnhancements does not want to use webbrowser.

**Pull request closed without merging**
