### PR TITLE
SublimeText 3/Python 3 compatibility

### PR DESCRIPTION
**Pull request by lettertwo**
These changes are _mostly_ for compatibility with Python 3. The 2to3 script did most of the work.

### CODE REVIEW

**Comment by lettertwo** [comment]
I've only tested these changes on OSX, and they do maintain backwards compatibility with SublimeText2 on OSX.

**Comment by titoBouzout** [comment]
OK, thanks.

If you are going to take the port of this plugin to ST3 that's fine for me, but please, includes support for ST2 too..

**Comment by JeanMertz** [comment]
Will this be merged into master soon?

**Comment by titoBouzout** [comment]
Soon is relative ...

**Comment by titoBouzout** [comment]
I just don't have time right now, but I'm allays willing to help, and pull request more than welcome <3, I just have my doubts that this still works in ST2.
This is the 3 most used Package http://wbond.net/sublime_packages/community#sort-installs wow! I'm very glad of my work and contributions, but if someone deletes a directory and that ends deleting a hard drive that would be terrible. I'm not saying, this pull request is not good, is just, that needs testing...
Hope yo can understand!

**Comment by zchrykng** [comment]
@titoBouzout If you pull it into a 'st3' branch you could get some help testing! ;)

**Comment by jeffjrare** [comment]
+1 for the new branch! If you could pull it into a python3 | st3 branch, we'll be able to test it live and help you ;)

**Comment by titoBouzout** [comment]
Let me try next week

**Comment by chonthu** [comment]
+1 for the new branch

**Comment by vasylnakvasiuk** [comment]
+1 for the new branch

**Comment by sbromberger** [comment]
+1 for the new branch. I can't move to ST3 without this plugin.

**Comment by cr0t** [comment]
+1

**Comment by titoBouzout** [comment]
There is now https://github.com/titoBouzout/SideBarEnhancements/tree/st3atyourownrisk
I'll freeze development on ST2 and start slowly introducing ST3, I'm sitll using ST2 and I've no clue of python3

**Comment by lettertwo** [comment]
Just rebased these changes onto https://github.com/titoBouzout/SideBarEnhancements/tree/st3atyourownrisk. Should make merging a little easier, if these are going to be merged.

**Comment by missedone** [comment]
cool, this pull request works on Windows 7 x64, thanks

**Comment by titoBouzout** [comment]
I pulled to st3atyourownrisk Thank you!

Please pull to that branch directlry, thanks!

**Comment by titoBouzout** [comment]
I'm reopening, because people can see there is some work in progress.

**Comment by titoBouzout** [comment]
Looks great now. Thanks a lot!

**Pull request closed without merging**
