### PR TITLE
Fixes relative path parsing

### PR DESCRIPTION
**Pull request by pilgerone**
Fixes a bug where paths relative to the project roots were treated as local files

### CODE REVIEW

**Comment by titoBouzout** [comment]
can you give an example of what you seeing and what you expect, thanks!

**Comment by pilgerone** [comment]
Of course!

With my `SideBarEnhancements.json` like
```
{
    "HTTP/public/": {
        "url_testing": "http://localhost/",
        "url_production": "https://mysite.com/"
    }
}

```
The previews go to  `file:///C:/absolute/project/path/HTTP/public/file.html` instead of `https://mysite.com/file.html` as one would expect.

Apparently the re.sub() isn't replacing the `url_path `in case of relative paths, since it requires the whole key to match at the beginning of `url_path`.

I'm on Windows, but by the logic of it, it should affect other OS too.

**Comment by titoBouzout** [comment]
ok, thank you, Im not completely sure if this will break something, as some people use relative paths when they use the configuration file in project/.sublime/SideBarEnhancements.json in any case we can fix it again :) thanks!

**Comment by pilgerone** [comment]
Oops, forgot about that option. My bad! ツ

I'm gonna make a new commit that works for `SideBarEnhancements.json` placed anywhere and for all OS path formats.

**Comment by titoBouzout** [comment]
Thanks :)

**Pull request merged**
