### PR TITLE
Updated Readme.md to include FAQ for what happens when all options optio...

### PR DESCRIPTION
**Pull request by bretterer**
...ns are grayed out.

I have run into this error a few times where i can not do anything in my sidebar enhancements.  The only way to resolve this is to remove the SidebarEnhancements.sublime-packge file from Installed Packages

### CODE REVIEW

**Comment by titoBouzout** [comment]
Hi bretterer! Thanks, I would like to suggest to add a bit more of information, this is to OSX specific, maybe a comment in the lines of "try reinstalling"  would be enough.

**Comment by bretterer** [comment]
titoBouzout:   I have tried the route of just reinstalling however this does not work.   After uninstalling, the settings file is still there.  The only way I have found to fix this is to remove the settings file and let sublime set it up again.

I am working on an update for this

**Comment by titoBouzout** [comment]
The install instructions already contain the line for the removal of the file. (this was lost in an update recently, I added it again, now)
Maybe keep the question but change the answer to reinstall? with a link to the install instructions?

**Comment by bretterer** [comment]
Should just close this then because reinstall does NOT work for this issue.... You HAVE to remove the file.

**Comment by titoBouzout** [comment]
Read the install instructions please, an updated version https://github.com/titoBouzout/SideBarEnhancements/tree/st3#installation

**Comment by bretterer** [comment]
Yup... I had just done these instructions.. and 5 minutes later (yesterday) No options available

**Comment by bretterer** [comment]
I just tried them again.. we will see how long it lasts this time

**Comment by bretterer** [comment]
This is what I am having an issue with... almost every other day I have to "reinstall" the package
screen shot 2013-08-12 at 10 50 58 am

**Comment by titoBouzout** [comment]
Do you have Package Control set to update packages automatically? We should try to tackle the issue instead of suggesting to remove the file, every time the package is broken.

**Comment by bretterer** [comment]
Nope... auto_upgrade is false

**Pull request closed without merging**
